additional checks

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -4,38 +4,63 @@ on:
   pull_request:
 
 jobs:
-  validate_and_build:
+  validate:
+    runs-on: ubuntu-latest
+    outputs:
+      matrix_dirs: ${{ steps.set_matrix.outputs.matrix_dirs }}
+    steps:
+    - uses: actions/checkout@v3
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+
+    - name: Validate number of directories
+      id: set_matrix
+      run: |
+        dirs=$(ls -d */ | sed 's|/||')
+        matrix_length=$(echo "$dirs" | wc -l)
+        expected_length=$(echo '[
+          "predicate-multisig",
+          "primitive_types",
+          "tuples",
+          "control_flow_if",
+          "constants",
+          "logging",
+          "base_asset",
+          "vector",
+          "enums",
+          "structs",
+          "control_flow_while_loop",
+          "compound_types",
+          "blockchain_types",
+          "control_flow_match_statement",
+          "solidity_cheatsheet",
+          "results",
+          "configurable_constants",
+          "uniswapv2",
+          "options",
+          "account_types",
+          "hello_sway",
+          "functions",
+          "cheatsheet",
+          "storage_map"
+        ]' | jq length)
+        
+        if [ $matrix_length -ne $expected_length ]; then
+          echo "Error: Number of directories ($matrix_length) does not match the expected count ($expected_length)"
+          exit 1
+        else
+          echo "Number of directories ($matrix_length) matches the expected count ($expected_length)"
+        fi
+        
+        echo "::set-output name=matrix_dirs::[$(echo $dirs | jq -R . | jq -s . | jq -c '.')]"
+
+  build_and_test:
+    needs: validate
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        dir: [
-          'predicate-multisig',
-          'primitive_types',
-          'tuples',
-          'control_flow_if',
-          'constants',
-          'logging',
-          'base_asset',
-          'vector',
-          'enums',
-          'structs',
-          'control_flow_while_loop',
-          'compound_types',
-          'blockchain_types',
-          'control_flow_match_statement',
-          'solidity_cheatsheet',
-          'results',
-          'configurable_constants',
-          'uniswapv2',
-          'options',
-          'account_types',
-          'hello_sway',
-          'functions',
-          'cheatsheet',
-          'storage_map'
-        ]
+        dir: ${{ fromJson(needs.validate.outputs.matrix_dirs) }}
 
-    name: Validate and Build ${{ matrix.dir }}
+    name: Build ${{ matrix.dir }}
     steps:
     - uses: actions/checkout@v3
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -57,17 +82,6 @@ jobs:
     - name: Set Fuelup environment and add component
       run: |
         fuelup default testnet
-
-    - name: Validate number of directories
-      run: |
-        matrix_length=$(echo "${{ toJson(strategy.matrix.dir) }}" | jq '. | length')
-        dir_count=$(ls -d */ | wc -l)
-        if [ $matrix_length -ne $dir_count ]; then
-          echo "Error: Number of directories ($matrix_length) does not match the count of directories ($dir_count)"
-          exit 1
-        else
-          echo "Number of directories ($matrix_length) matches the expected count ($dir_count)"
-        fi
 
     - name: Build in ${{ matrix.dir }}
       run: |
